### ISSUE TITLE
Can this factor 768 bit integers?

### ISSUE THREAD

**Issue by ACK-J** [eniac/faas#13]
Can a modification to this repository factor 768 bit integers? If not do you know of another repository or tool that can handle 768? My understanding is that 768 bit has been broken for at least a decade but I can't find any tools to factor it.

**Comment by lukevalenta** [comment]
Theoretically, but I wouldn't recommend it. It took about two years on a dedicated lab cluster to factor RSA-768 back in 2009. It would probably take a fraction of the time now, but I'd still be scared of the AWS bill if you use rented cloud compute for it.

If I were starting from scratch and wanted to factor a 768-bit integer, I'd use [Cado-NFS](https://gitlab.inria.fr/cado-nfs/cado-nfs) (which this project is essentially a wrapper around), as that project is still well-maintained and has another 10 years of code improvements since this project was launched (probably making the patches we applied on top of it unnecessary). See https://gitlab.inria.fr/cado-nfs/cado-nfs#big-factorization-200-digits-and-more for some tips for factoring large numbers.

**Comment by ACK-J** [comment]
Much appreciated!
